version: '3.8'

services:
  web:
    container_name: web
    build:
      context: ./web
    env_file:
      - ./web/.env
    ports:
      - "3000:3000"
    depends_on:
      - api

  api:
    container_name: api
    build:
      context: ./api
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
